### ISSUE TITLE
NullPointerException in com.github.hycos.regex2smtlib.Translator.render(Translator.java:149)

### ISSUE THREAD

**Issue by traceprobe** [hycos/regex2smtlib#1]
Hello,
I tried the examples of Translator.INSTANCE.translateToClause and Translator.INSTANCE.translateToConstraint, both of which cause a NullPointerException.

java.lang.NullPointerException
	at com.github.hycos.regex2smtlib.Translator.render(Translator.java:149)
	at com.github.hycos.regex2smtlib.Translator.translateToClause(Translator.java:107)

It seems that the code fails to instantiate a MustacheEngine object. 

thanks

**Comment by julianthome** [comment]
Hi @traceprobe, thank you very much for the report and sorry for the late reply. Will fix that asap.

**Comment by julianthome** [comment]
Thanks @traceprobe, the last patch should have fixed the issue. I will also deploy a new release `1.1` on maven central soon.

**Comment by julianthome** [comment]
Done: https://oss.sonatype.org/content/repositories/releases/com/github/hycos/regex2smtlib/1.1/
